name: coloc
description: Find your ideal university roommate with our easy-to-use app. Match based on preferences for a perfect living experience.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  modal_progress_hud: ^0.1.3
  numberpicker: ^2.1.1
  image_picker: ^0.8.0+4
  firebase_storage: ^8.1.3
  firebase_core: ^1.3.0
  firebase_auth: ^1.4.1
  cloud_firestore: ^2.2.2
  percent_indicator: ^3.0.1
  shared_preferences: ^2.0.6
  provider: ^5.0.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - images/
  fonts:
    - family: GoogleSans
      fonts:
        - asset: fonts/GoogleSans-Regular.ttf
        - asset: fonts/GoogleSans-Medium.ttf
        - asset: fonts/GoogleSans-Bold.ttf
        - asset: fonts/GoogleSans-Italic.ttf
        - asset: fonts/GoogleSans-BoldItalic.ttf
        - asset: fonts/GoogleSans-MediumItalic.ttf
